feat/#13-주행정지(휴식)화면 구현
DeveloperAcademy-POSTECH/2024-MacC-A9-DOMADO2 pull request #32
Opened 2024-10-12 18:02 UTC by kojaebo

## 🔴 변경 사항 (What)
> 구현한 새로운 기능이나 수정사항을 나열합니다.
- 주행 정지(휴식)시 현재 휴식시간을 타이머로 표시합니다.
- 현재까지의 주행시간을 표시합니다.
- 현재까지의 주행거리를 표시합니다.
- 주행을 재개하는 버튼을 보여줍니다.
- 주행을 종료하는 버튼을 보여줍니다.
- 주행 종료를 짧게 누를시 길게누르라는 알림을 보여줍니다.

## 🟠 변경 이유 (Why)
> 이 변경이 필요한 이유나 해결하려는 문제를 설명합니다.

## 🟡 테스트 방법 (How to Test)
> 변경사항을 검증하는 방법을 단계별로 설명합니다.

## 🔵 스크린샷 (Visual Proof) (Optional)
> **UI 변경이 있는 경우**, 변경 전후를 시각적으로 비교합니다.

<img width="234" alt="스크린샷 2024-10-13 오전 2 56 04" src="https://github.com/user-attachments/assets/a7a04c18-8edf-4bba-bbd3-2b9ef350dd54">
<img width="238" alt="스크린샷 2024-10-13 오전 3 00 31" src="https://github.com/user-attachments/assets/724b2461-430b-492c-9a21-d36a951317a7">

## 🟢 추가 노트 (Additional Notes)
> 검토자가 알아야 할 기타 중요한 정보를 제공합니다.

2024-10-13 03:37 UTC, OneMoreThink requested changes
밤새 고생많으셨어요 ㅎㅎ
리뷰사항 확인하시고 수정 부탁드립니다. 
향후 길게누르라는 알림이 뜬 이후 일정시간이 지나면 자동으로 사라지는 기능과 각 버튼별 햅틱 피드벡도 고려해보세요~~~

2024-10-13 03:37 UTC, OneMoreThink commented on DomadoV/DomadoV/View/PauseRideView.swift
> +        NavigationView {
현재 각 화면간의 전환은 화면을 담당하는 `ViewModel`이 `AppCoordinator`에게 `RideEvent`를 발행하고 이후 해당 이벤트를 `AppCoordinator`가 수신하여 CurrentView를 교체하고 이를 `ContentView`에서 반영하는 흐름으로 진행되고 있습니다. 
**따라서 현재 `NavigationView`를 통한 화면 계층구조 관리가 불필요하므로 제거해야합니다.**

2024-10-13 03:37 UTC, OneMoreThink commented on DomadoV/DomadoV/View/PauseRideView.swift
> +    @State private var isActive = false
`isActive` 변수의 용도가 뭘까요??

2024-10-13 03:37 UTC, OneMoreThink commented on DomadoV/DomadoV/View/PauseRideView.swift
> +                .customFont(.baseTimeDistanceNumber)
customFont에 이미 각 텍스트별 폰트, 크기, opacity가 모두 정의되어 있습니다. 
따라서 별도 수정자를 통해 설정할 필요가 없습니다.

2024-10-13 03:37 UTC, OneMoreThink commented on DomadoV/DomadoV/View/PauseRideView.swift
> +                    self.isActive = true
`isActive` 동작에 대한 설명이 필요해요~~

2024-10-13 03:37 UTC, OneMoreThink commented on DomadoV/DomadoV/View/PauseRideView.swift
> +            ZStack {
`alertView`구성시 ZStack 보다 alertContent 에 overlay(alignment: .topTrailing) { ... } 을 활용해보세요😁

2024-10-13 12:32 UTC, kojaebo commented on DomadoV/DomadoV/View/PauseRideView.swift
> +    @State private var isActive = false
다른 뷰로 이동할 때 필요할 것이라 생각했었는데요,, 더 고민해보겠습니다,,

2024-10-13 12:37 UTC, kojaebo commented on DomadoV/DomadoV/View/PauseRideView.swift
> +                    self.isActive = true
멈춤버튼을 길게 눌러 주행을 종료했을 때에, NavigationLink로 화면 이동시키는 역할을 할 것이라 생각했지만, 수정해보겠습니다

2024-10-13 12:39 UTC, OneMoreThink commented on DomadoV/DomadoV/View/PauseRideView.swift
> +                    self.isActive = true
그랬군요 ㅎㅎ, 그럼 내일 화면 전환 로직에 대해 좀 더 자세히 설명해 드리도록 하겠습니다. 😎

2024-10-13 13:06 UTC, kojaebo commented on DomadoV/DomadoV/View/PauseRideView.swift
> +                    self.isActive = true
감사합니다!!!

2024-10-15 17:22 UTC, kojaebo commented on DomadoV/DomadoV/View/PauseRideView.swift
> +        NavigationView {
NavigationView 제거하였습니다!

2024-10-15 17:23 UTC, kojaebo commented on DomadoV/DomadoV/View/PauseRideView.swift
> +            ZStack {
overlay 적용하였습니다!!

2024-10-15 17:23 UTC, kojaebo commented on DomadoV/DomadoV/View/PauseRideView.swift
> +                .customFont(.baseTimeDistanceNumber)
폰트 수정하였습니다!

2024-10-16 01:35 UTC, OneMoreThink reviewed
isActive 프로퍼티 관련한 부분만 해결되면 바로 머지 가능할 것 같습니다. 🥸

2024-10-16 11:15 UTC, kojaebo commented on DomadoV/DomadoV/View/PauseRideView.swift
> +    @State private var isActive = false
프로퍼티 삭제하였습니다!

2024-10-16 11:15 UTC, kojaebo commented on DomadoV/DomadoV/View/PauseRideView.swift
> +                    self.isActive = true
코드 삭제하였습니다!

2024-10-16 15:52 UTC, OneMoreThink approved these changes
현재 PauseRideView에서 @State 로 관리하고 있는 `showAlert`속성을 viewModel에서 @Published를 통해 제어하는 방법으로 화면에 대한 제어를 모두 viewModel에서 관리하도록 할 수 있습니다. 

고생하셨어요. 머지 갑시당

2024-10-17 01:38 UTC, merged